# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Oana Pintoiu
title: Ex-Transformations Programme Manager
email: oana.pintoiu@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  oanapintoiu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: oanapintoiu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
 # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Oana (Wah'nah)) and I'm an experienced programme manager with a passion for tech. Here's a bit more about me:

My flex? Really fast learner. My research skills and the ability to quickly absorb information have allowed me to successfully deliver and work on projects across several industries, such as education, healthcare, and now the automation industry. 

My greatest skill? Big-picture thinking - being able to grasp abstract ideas and possibilities, turn into a complete perspective that I can then efficiently plan, strategize and deliver on alongside the right stakeholders. 

My working style? Hybrid Project Management, a mix in between traditional and agile methods. 

What my team(s) say about me? I'm supportive, a good listener, easy to talk to, reliable, present, and very passionate about getting the job done right, on time, and on budget.

 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  title
            # icon: 
            url: url
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          sum up in one sentece
        description: | # this will include new lines to allow paragraphs
         description

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: title
        link: link
        # link_text: boringcompany.com
        sub_title: role
        caption: November 2017 - Present
        quote: >
          sum up in one sentece
        description: | # this will include new lines to allow paragraphs
           description

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University
        caption: 2014 - 2017
        sub_title: BSc Renewable Energy Syste,s
        quote: >
          sum up in one sentece
        description: | # this will include new lines to allow paragraphs
          description

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
 

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
